version: '3'
services:
  postgresql_db:
    restart: always
    container_name: drf_db
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - yatube_api_data:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:${DB_PORT}'
    networks:
      - yatube_api_network
    env_file:
      - .env
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    networks:
      - yatube_api_network
    env_file:
      - .env
  backend:
    restart: always
    container_name: drf_backend
    image: yamdb_final
    build:
      context: ../api_yamdb
      dockerfile: Dockerfile
    volumes:
      - ../api_yamdb:/app
    command: bash -c "cd /app &&
      python manage.py migrate --noinput &&
      python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgresql_db
    networks:
      - yatube_api_network
    ports:
      - '8000:8000'
    env_file:
      - .env
networks:
  yatube_api_network:

volumes:
  yatube_api_data:
  static_volume: